{
 'name' : 'Sales_ept',
 'version' : '1.0',
 'depends' : ['sale_crm'],
 'author' : 'Raumil D',
 'description' : 'This is product_category_ept',
 'data' : ['Security/security.xml','Security/ir.model.access.csv',
           'Views/pro_cat.xml',
           'Views/product_uom_cat.xml',
           'Views/product_uom.xml',
           'Views/product.xml',
           'Views/res_parter_sales.xml',
           'Views/sale_order.xml',
           'Views/order_line.xml',
           'Views/crm_lead.xml',
           'Views/crm_lead_line.xml',
           'Views/crm_team.xml',
           'Views/warehouse.xml',
           'Views/location.xml',
           'Views/move.xml',
           'Views/inventory.xml',
           'Views/picking.xml',
           'Views/picking_sequence.xml',
           'Views/inventory_line.xml',
           'Wizard/wizard.xml',
           'Views/tax.xml',
           'Views/menu.xml'],
 'demo' : [],
 'installable' : True
}