{
    'name': 'Sales_ept',
    'version': '',
    'depends': ['sale_crm'],
    'author': "Emipro Technologies (P) Ltd.",
    'license':'',
    'description': """Sales by Emipro Technologies providing
     more functional features
     than basic Sale module.""",
    'data': ['security/security.xml', 'security/ir.model.access.csv',
             'views/pro_cat.xml',
             'views/product_uom_cat.xml',
             'views/product_uom.xml',
             'views/product.xml',
             'views/res_parter_sales.xml',
             'views/sale_order.xml',
             'views/order_line.xml',
             'views/crm_lead.xml',
             'views/crm_lead_line.xml',
             'views/crm_team.xml',
             'views/warehouse.xml',
             'views/location.xml',
             'views/move.xml',
             'views/inventory.xml',
             'views/picking.xml',
             'views/picking_sequence.xml',
             'views/inventory_line.xml',
             'wizard/wizard.xml',
             'views/tax.xml',
             'views/menu.xml'],
    'demo': [],
    'installable': True
}
